packages:
  - browser
  - cli
  - shared
  - monitor
  - pixel/packages/*
  - pixel/packages/native/*
  - pixel/examples/*
linkWorkspacePackages: true
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - '@zenbu-labs/pixel'
